spring:
  profiles:
    active: '@activatedProperties@'

  datasource:
    tomcat:
      max-active: 8
      max-idle: 2
      max-wait: 5000
      remove-abandoned: true
      remove-abandoned-timeout: 30
      log-abandoned: true
  devtools:
    restart:
      trigger-file: reload
    livereload:
      enabled: true
  jackson:
    default-property-inclusion: NON_NULL
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format-sql: true
        show-sql: true
      ddl-auto: none


server:
  servlet:
    context-path: @project.contextPath@

project:
  jwt:
    signKey: Bu:GW8bgPlEw
    expirationMinutes: 15   # Short time to avoid security issues in case of JWT leaking

